# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KTdatJOjUEGHtNlTqApVX5PrdY25OAS3TczbzGKuDHMYUzq+hfEAus8czYfDl2C30OyWBPS0GBH4EpoYuTy6KTepjrqgcKbVHNGMn6MqoUH5xkhSOgcHeYpKvIGnjdNglu41ChU//qPcXHiUAo3LgFp9R/Kd5hHL0BtSsFxMc9OMfLBZn5nK8DlzVSrXEEv/W/VguCAeuiZ8n624r/AlRWQCW4/QiBMcAhclsVtRXCpvmC3SScV7Ny+4GDA2RD7W2OINVGPN3jOamZo4xDQbSLrmurTBFq1Wiyu17/W0Qgt3ty2T2G+GHxces/b4c1IrzZ3OFBZjAoXnrccIC69qU+JvzVdn9OCz7RudT2QCqwzFiSEDBdsOhwebdDCmRfRRPXjUu+QdGSmUZEWp0MsziskK38JSvRUbmrvX2QVeV2nLrUuzp6oHJgZKGvuhq4pfetvSpJnueYzC26xWBFA1JcJrvLZcU+uZttS9C6pnflbuEajdCPHUarb9KspEVjkCehS+WX2wS6WUpGXxkPhaoFzeSKPYkOcTk60WVoo7ov0ge3sciH9egpneneBwvTBE5XGxRNxYVbbS+x3N7WFMLhUKIGd1vg8Gda2WrK6zGk0wwKzyc10fCLTSpLI6Pbmmrz5fYjDy9VYOtjVvaiFhLl4o7q84vqMurUxF3vjulZY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
