travis:
  secure:
    BINSTAR_TOKEN: KTdatJOjUEGHtNlTqApVX5PrdY25OAS3TczbzGKuDHMYUzq+hfEAus8czYfDl2C30OyWBPS0GBH4EpoYuTy6KTepjrqgcKbVHNGMn6MqoUH5xkhSOgcHeYpKvIGnjdNglu41ChU//qPcXHiUAo3LgFp9R/Kd5hHL0BtSsFxMc9OMfLBZn5nK8DlzVSrXEEv/W/VguCAeuiZ8n624r/AlRWQCW4/QiBMcAhclsVtRXCpvmC3SScV7Ny+4GDA2RD7W2OINVGPN3jOamZo4xDQbSLrmurTBFq1Wiyu17/W0Qgt3ty2T2G+GHxces/b4c1IrzZ3OFBZjAoXnrccIC69qU+JvzVdn9OCz7RudT2QCqwzFiSEDBdsOhwebdDCmRfRRPXjUu+QdGSmUZEWp0MsziskK38JSvRUbmrvX2QVeV2nLrUuzp6oHJgZKGvuhq4pfetvSpJnueYzC26xWBFA1JcJrvLZcU+uZttS9C6pnflbuEajdCPHUarb9KspEVjkCehS+WX2wS6WUpGXxkPhaoFzeSKPYkOcTk60WVoo7ov0ge3sciH9egpneneBwvTBE5XGxRNxYVbbS+x3N7WFMLhUKIGd1vg8Gda2WrK6zGk0wwKzyc10fCLTSpLI6Pbmmrz5fYjDy9VYOtjVvaiFhLl4o7q84vqMurUxF3vjulZY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
