travis:
  secure:
    BINSTAR_TOKEN: LP5cRvIW4Ux4Aioy5Cvup9t9ra9D0Xi52BeIMRZcJjYoEtKMTziV3yGNg/qBAlIppJaWh/8GU1ej4b+hj9ieS+SQj9UaQIIp3E4JUl3b5hqcR44Vf3+7KpEVAlpOtPviPr9avj4PvnWk+z+qOhGhFOLFM8jtVeDTe6hnXn7fN9Nj8z0xxqrgh2wzyh8c4aYFtJQ55QtEXmpUmTOFb1HsULhC4gDV2S8gCss2qByy8LytkkriY1irCCY0RUIDimWZiaIXhrKtJVOa3hdH8SHdMsXBRoIKy6wgOqDZzOFi3KNPHQsu7n6Ojh13LC1GtMQfngkUB7cUI2pmfLDUpRdxXioHTHKzHDJQEfFrOWHuEhElwcvE/p4aJ5hJyfFeRwd3KpvwHFa/YJS+hHkV9Z+6wAXtYeXHgcGVX67OMfAnAtV1dyA5RFtgLjKSr6tO6Ap83OKxx52CCMBCLiszGaDuZW/+cJnzPnnx+DgoBpI6vApQsiJaQUASXEzARYP0RSYTzqw10IN3SjIYXhkZ5RHAjdOXIxjqHxNNJDnswd2R41G+3TcWkYohbBjy+S0WAof/9yZBPnfAeVM6i3hAF0ESNN5c6/J4qqejfWwEeaJRgPGr3izxGmbkmNM+2nrW8lBObITV6jCAmW4t76QNfS9seh4mYGJc8kjEJ4K7v2p34jM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
